# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(748, 441)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cipherButton = QtWidgets.QPushButton(self.centralwidget)
        self.cipherButton.setGeometry(QtCore.QRect(40, 220, 75, 23))
        self.cipherButton.setObjectName("cipherButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.decipherButton = QtWidgets.QPushButton(self.centralwidget)
        self.decipherButton.setGeometry(QtCore.QRect(590, 220, 75, 23))
        self.decipherButton.setObjectName("decipherButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 270, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 70, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 180, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(330, 230, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(450, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.keyA = QtWidgets.QLineEdit(self.centralwidget)
        self.keyA.setGeometry(QtCore.QRect(310, 200, 113, 21))
        self.keyA.setObjectName("keyA")
        self.keyB = QtWidgets.QLineEdit(self.centralwidget)
        self.keyB.setGeometry(QtCore.QRect(310, 250, 113, 21))
        self.keyB.setObjectName("keyB")
        self.cipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.cipherText.setGeometry(QtCore.QRect(43, 99, 201, 101))
        self.cipherText.setObjectName("cipherText")
        self.cipherResult = QtWidgets.QTextEdit(self.centralwidget)
        self.cipherResult.setGeometry(QtCore.QRect(40, 290, 201, 101))
        self.cipherResult.setObjectName("cipherResult")
        self.decipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.decipherText.setGeometry(QtCore.QRect(450, 100, 201, 101))
        self.decipherText.setObjectName("decipherText")
        self.decipherResult = QtWidgets.QTextEdit(self.centralwidget)
        self.decipherResult.setGeometry(QtCore.QRect(450, 290, 201, 101))
        self.decipherResult.setObjectName("decipherResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 748, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Šifrovanie:"))
        self.label_2.setText(_translate("MainWindow", "Zadaj text na šifrovanie"))
        self.cipherButton.setText(_translate("MainWindow", "ŠIFRUJ"))
        self.label_3.setText(_translate("MainWindow", "Výsledok šifrovania"))
        self.decipherButton.setText(_translate("MainWindow", "DEŠIFRUJ"))
        self.label_4.setText(_translate("MainWindow", "Výsledok dešifrovania"))
        self.label_5.setText(_translate("MainWindow", "Zadaj text na dešifrovanie"))
        self.label_6.setText(_translate("MainWindow", "Zadaj kľúč A"))
        self.label_7.setText(_translate("MainWindow", "Zadaj kľúč B"))
        self.label_8.setText(_translate("MainWindow", "Dešifrovanie:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

